#!/bin/bash

key='A really SECURE key that no one will guess.'

time cat whatIsThis.jpg | ./phpShift.php e "$key" > test_encrypted.jpg
time cat test_encrypted.jpg | ./phpShift.php d "$key" > test_decrypted.jpg

md5sum whatIsThis.jpg test_decrypted.jpg

rm test_*jpg
